### ISSUE TITLE
Block Updating

### ISSUE THREAD

**Issue by ErfinderLabyrinth** [jeremiahwinsley/ExMachinis#13] opened 2022-11-02 12:36 UTC
If I place the Flux hammer first and than the Chest, it is not accepted

Please check the errors every blockupdate

**Comment by jeremiahwinsley** [comment] 2022-11-03 01:54
Duplicate of #4 - validation is currently done at the beginning of a work cycle, so it can take up to 8 seconds for the error to go away. I do plan to make it run more often,

**Closed as not planned by jeremiahwinsley** 2022-11-03 01:54 UTC
Labels: duplicate

**Comment by ErfinderLabyrinth** [comment] 2022-11-03 10:21
sorry i have no read the other post, only the title
